### ISSUE TITLE
1.06, F0.7.5, PF2 - some macros are escaping from the Default folder, cannot be filtered to it

### ISSUE THREAD

**Issue by apoapostolov** [ardittristan/VTTMacroEditor#2]
I noticed that a lot of player created Macros from items in PF2 are not properly marked as unassigned and not put into the Default folder. 

![image](https://user-images.githubusercontent.com/4083812/97869075-7e94c900-1d19-11eb-94ce-7ae4e9ce1ecd.png)

My export:

{"hidden":{"macroList":["1YzxXL5HUrLh1DSr","1xBVdHaxCHCRdB7q","6ZOAfsVwae6hJKkh","9NitpkfLcNYJSuxk","L665Hsi9HfCP1STO","TL6pHZFzqmPcp10T","TM7iOAJCtOQj2fLE","UkpJBMwSfTLWtZNw","Yfm2mKbMTrAkgpS1","fFO0ZmElEN9gMBU2","goIHvtB3fUWBFHuT","huWzVS2dzgg8IzjX","lufzkxtANLsHckly","qUg4cBQbQgBK6bJz","rVE9nazprLSizrif","zbxkCyzfL20G8qmS"],"titleText":"hidden-macros"},"mfolder_cxfpg57jxto":{"titleText":"For GM","colorText":"#77007d","macroList":["1OXDiNyojmjbLDYA","4Ea0cLscEyFy9F8Y","7dAekeLz6WrxYB6t","ASlDhky7ruqyAJi0","HGfy5rxTjtxMMdhX","J2lRcmtlcJQXYHBa","Qr0yl7ct1tDEgZCl","RY1mlxxnmYCpgzoD","aZEk00YVorAh2zk4","azPvgGuFCksQD7aS","gzOv3eDTd91IbVKg","jidEWzH20CBkc0Rk","kZxQeSzNJf8Yqq2f","nHfQZZTGlcsZBbcE","nZJ7NDSkR6BvatLI"],"folderList":[],"_id":"mfolder_cxfpg57jxto","pathToFolder":[],"folderIcon":null},"mfolder_mpy25rysips":{"titleText":"For Players","colorText":"#7d0003","macroList":["3jQCQ9ZJytz0gTAN","6hM1wPBKdxb2dgzb","HPERcPchI5OieEVL","NrD5sI45OLln8WXg","i2ql99TeLLhw08u9","l5hUyK8OQJNLfxNd","sCOjVaBsB3r5vWS4"],"folderList":[],"_id":"mfolder_mpy25rysips","pathToFolder":[],"folderIcon":null},"default":{"macroList":[],"titleText":"Default","colorText":"#000000","_id":"default"},"mfolder_m8qmqgcm7nd":{"titleText":"Custom Conditions","colorText":"#970081","macroList":["DTWvynM3hM4Gjpn5","PJXJ84xCyDMvGVpy","VrISMXS1wAbe0EkH"],"folderList":[],"_id":"mfolder_m8qmqgcm7nd","pathToFolder":[],"folderIcon":null,"playerDefault":null}}

**Comment by ardittristan** [comment]
This module only adds the intellisense editor window to the macro editor. It does not add macro folders, so it shouldn't be causing any issues with folders. Especially since it only interacts with the html input box and not with the macro object itself. Maybe the issue lies in the module that adds folders?

**Comment by apoapostolov** [comment]
I am very sorry, I posted this to the wrong github
