### ISSUE TITLE
FR: Optional double-space instead of tab

### ISSUE THREAD

**Issue by RollToSaveVsDragons** [ardittristan/VTTMacroEditor#3]
I really like this editor. Thanks for making it. One thing that annoys me is the tabs. Could we get an option to get rid of tabs altogether and just put in two spaces whenever a tab would be added, be it auto-indent or hitting tab?

**Comment by ardittristan** [comment]
I tried to fix it, but even when I hard enable soft tabs (which uses spaces) it still turns it into tabs when the length is 4

**Comment by RollToSaveVsDragons** [comment]
Thank you for trying.

**Comment by ardittristan** [comment]
Issue should move to acelib repo if still valid
